"""Create projet table

Revision ID: 368e77a66bb2
Revises: 
Create Date: 2025-06-11 19:33:27.523784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368e77a66bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('tech', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projet')
    # ### end Alembic commands ###
